import { useState, useCallback, useRef, useEffect } from 'react'
import { Canvas } from '@react-three/fiber'
import { AnimatePresence, motion } from 'framer-motion'
import Scene from './components/Scene'
import InfoModal from './components/InfoModal'
import EditModal from './components/EditModal'
import TopNav from './components/TopNav'
import Intro from './components/Intro'
import { buildings as defaultBuildings, person } from './data/profile'
import { saveEdit, loadAllEdits } from './utils/editStore'

// Edit mode is only available during local development (npm run dev).
// Production builds (Vercel / anything public) never expose the editor.
const isEditMode =
  import.meta.env.DEV &&
  typeof window !== 'undefined' &&
  window.location.search.includes('edit')

export default function App() {
  const [showIntro,        setShowIntro]        = useState(true)
  const [cameraMode,       setCameraMode]       = useState('helicopter')
  const [selectedBuilding, setSelectedBuilding] = useState(null)
  const [editTarget,       setEditTarget]       = useState(null)
  const [buildings,        setBuildings]        = useState(defaultBuildings)
  const [showHint,         setShowHint]         = useState(true)
  const sceneRef = useRef()

  // Load persisted edits from IndexedDB on mount
  useEffect(() => {
    loadAllEdits().then(edits => {
      if (!edits || Object.keys(edits).length === 0) return
      setBuildings(prev => prev.map(b => {
        const edit = edits[b.id]
        if (!edit) return b
        return { ...b, ...edit }
      }))
    }).catch(() => {})
  }, [])

  const handleEnter = useCallback(() => {
    setShowIntro(false)
    setCameraMode('street')
  }, [])

  const handleSelect    = useCallback(b => { setSelectedBuilding(b); setShowHint(false) }, [])
  const handleClose     = useCallback(() => setSelectedBuilding(null), [])
  const handleEditOpen  = useCallback(b => { setSelectedBuilding(null); setEditTarget(b) }, [])
  const handleEditClose = useCallback(() => setEditTarget(null), [])

  const handleSave = useCallback((id, updatedFields) => {
    setBuildings(prev => prev.map(b => b.id === id ? { ...b, ...updatedFields } : b))
    saveEdit(id, updatedFields).catch(() => {})
    setSelectedBuilding(prev => prev?.id === id ? { ...prev, ...updatedFields } : prev)
  }, [])

  // Export all current edits (text + uploaded images) as a downloadable profile.js
  const handleExport = useCallback(() => {
    const personJson   = JSON.stringify(person,    null, 2)
    const buildingsJson = JSON.stringify(buildings, null, 2)
    const content = [
      '// AUTO-GENERATED by Export My Changes — replace src/data/profile.js with this file.',
      `export const person = ${personJson}`,
      '',
      `export const buildings = ${buildingsJson}`,
      '',
    ].join('\n')
    const blob = new Blob([content], { type: 'text/javascript' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = 'profile.js'
    a.click()
    URL.revokeObjectURL(url)
  }, [buildings])

  const enrichedSelected = selectedBuilding
    ? buildings.find(b => b.id === selectedBuilding.id) ?? selectedBuilding
    : null

  return (
    <>
      {/* 3D Canvas — always rendering (visible behind intro blur) */}
      <div style={{ position:'fixed', inset:0, zIndex:0, touchAction:'none' }}>
        <Canvas
          shadows
          camera={{ position:[0,40,0], fov:75, near:0.1, far:500 }}
          gl={{ antialias:true }}
          style={{ background:'#87ceeb', touchAction:'none' }}
          onPointerMissed={handleClose}
        >
          <Scene
            ref={sceneRef}
            selectedBuilding={enrichedSelected}
            onSelect={handleSelect}
            isEditMode={isEditMode}
            onEdit={handleEditOpen}
            buildings={buildings}
            cameraMode={cameraMode}
          />
        </Canvas>
      </div>

      {/* Intro overlay (blurred helicopter view behind) */}
      <AnimatePresence>
        {showIntro && <Intro key="intro" onEnter={handleEnter} />}
      </AnimatePresence>

      {/* Street-mode UI */}
      <AnimatePresence>
        {!showIntro && (
          <>
            <motion.div key="nav" initial={{opacity:0,y:-16}} animate={{opacity:1,y:0}} transition={{delay:0.2}}>
              <TopNav />
            </motion.div>

            <AnimatePresence>
              {showHint && (
                <motion.div key="hint"
                  initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}}
                  transition={{delay:0.5}}
                  style={{
                    position:'fixed', bottom:28, left:'50%', transform:'translateX(-50%)',
                    zIndex:100, display:'flex', alignItems:'center', gap:8,
                    padding:'9px 20px', background:'rgba(5,11,24,0.85)',
                    border:'1px solid rgba(0,120,212,0.28)', borderRadius:24,
                    fontSize:13, color:'#7a9ab8', backdropFilter:'blur(12px)',
                    whiteSpace:'nowrap', pointerEvents:'none',
                    fontFamily:'Inter,-apple-system,sans-serif',
                  }}>
                  <span style={{width:6,height:6,borderRadius:'50%',background:'#50E6FF',
                    animation:'pulse 2s ease-in-out infinite'}} />
                  Swipe to look · ▲▼ to walk · Tap a door to explore
                  {isEditMode && <span style={{color:'#ffd700',fontWeight:600,marginLeft:4}}>· Edit mode active</span>}
                </motion.div>
              )}
            </AnimatePresence>

            {/* Navigation arrows — bottom-right */}
            <div style={{
              position: 'fixed', bottom: 32, right: 32, zIndex: 200,
              display: 'flex', flexDirection: 'column', gap: 8,
            }}>
              {[['▲','forward','Walk forward'],['▼','backward','Walk back']].map(([icon,dir,tip]) => (
                <button key={dir} title={tip}
                  onClick={() => sceneRef.current?.navigate(dir)}
                  style={{
                    width: 48, height: 48, borderRadius: 12,
                    background: 'rgba(5,11,24,0.88)',
                    border: '1px solid rgba(0,120,212,0.45)',
                    color: '#50E6FF', fontSize: 20, cursor: 'pointer',
                    backdropFilter: 'blur(12px)',
                    boxShadow: '0 2px 14px rgba(0,0,0,0.5)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontFamily: 'Inter,-apple-system,sans-serif',
                  }}>
                  {icon}
                </button>
              ))}
            </div>

            <InfoModal building={enrichedSelected} onClose={handleClose} isEditMode={isEditMode} onEdit={handleEditOpen} />

            {/* Export button — edit mode only, bottom-left */}
            {isEditMode && (
              <button
                onClick={handleExport}
                title="Download all your edits as a profile.js file to push to Vercel"
                style={{
                  position:'fixed', bottom:32, left:32, zIndex:300,
                  display:'flex', alignItems:'center', gap:8,
                  padding:'11px 20px', borderRadius:12,
                  background:'#ffd700', border:'none',
                  color:'#0a0a0a', fontSize:13, fontWeight:700,
                  cursor:'pointer', fontFamily:'Inter,-apple-system,sans-serif',
                  boxShadow:'0 4px 20px rgba(255,215,0,0.4)',
                }}
              >
                ⬇ Export My Changes
              </button>
            )}
          </>
        )}
      </AnimatePresence>

      <EditModal building={editTarget} onClose={handleEditClose} onSave={handleSave} />
    </>
  )
}
